# Test cases are disabled in this driver. It is recommended to test the driver with Staging Central and Dev Central
# before publishing to Ballerina Central.
name: Publish Release

on:
  workflow_dispatch:
  repository_dispatch:
    types: [stdlib-release-pipeline]

jobs:
  call_workflow:
    name: Run Release Workflow
    if: ${{ github.repository_owner == 'ballerina-platform' }}
    uses: ballerina-platform/ballerina-library/.github/workflows/release-package-template.yml@main
    secrets: inherit
    with:
      package-name: mysql.driver
      package-org: ballerinax
